version: '3.8'

services:
  # Solr with LTR support (overriding Chorus default)
  solr:
    image: o19s/hello-ltr-solr:latest
    container_name: solr-ltr
    ports:
      - "8983:8983"
    environment:
      - SOLR_HEAP=4g
      - SOLR_OPTS=-Dsolr.modules=ltr
    volumes:
      - solr_data:/var/solr/data
      - ./solr-configs:/opt/solr/server/solr/configsets/custom
      - ./solr-schema:/opt/solr/contrib/ltr/schema
    networks:
      - search_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Vector embedding service
  embedding-service:
    image: sentence-transformers/all-MiniLM-L6-v2
    container_name: embedding-service
    ports:
      - "8080:8080"
    environment:
      - MODEL_NAME=all-MiniLM-L6-v2
    networks:
      - search_network
    command: python -m sentence_transformers.server --model all-MiniLM-L6-v2 --port 8080

  # StormCrawler for web crawling
  stormcrawler:
    image: apache/storm:2.4.0
    container_name: storm-crawler
    depends_on:
      - solr
    volumes:
      - ./storm-configs:/storm-configs
      - ./crawler-topology:/crawler-topology
    networks:
      - search_network
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper:2181
      - STORM_NIMBUS_SEEDS=nimbus
    command: >
      bash -c "
        storm jar /crawler-topology/crawler-solr-1.0.jar 
        org.apache.stormcrawler.solr.SolrCrawlTopology 
        -conf /storm-configs/crawler-conf.yaml 
        crawler-topology
      "

  # Zookeeper for Storm coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - search_network

  # Storm Nimbus
  nimbus:
    image: apache/storm:2.4.0
    container_name: storm-nimbus
    depends_on:
      - zookeeper
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper:2181
    networks:
      - search_network
    command: storm nimbus

  # Storm Supervisor
  supervisor:
    image: apache/storm:2.4.0
    container_name: storm-supervisor
    depends_on:
      - nimbus
      - zookeeper
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper:2181
      - STORM_NIMBUS_SEEDS=nimbus
    networks:
      - search_network
    command: storm supervisor

  # Storm UI
  storm-ui:
    image: apache/storm:2.4.0
    container_name: storm-ui
    depends_on:
      - nimbus
    ports:
      - "8081:8080"
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper:2181
      - STORM_NIMBUS_SEEDS=nimbus
    networks:
      - search_network
    command: storm ui

  # Redis for URL frontier (StormCrawler)
  redis:
    image: redis:7-alpine
    container_name: redis-frontier
    ports:
      - "6379:6379"
    networks:
      - search_network
    command: redis-server --appendonly yes

volumes:
  solr_data:

networks:
  search_network:
    driver: bridge
